export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: 'Keke Models' | 'Spare Parts' | 'Accessories';
  brand: 'Bajaj' | 'TVS' | 'Piaggio' | 'Generic';
  image: string;
  aiHint: string;
  rating: number;
  reviewsCount: number;
  stockStatus: 'In Stock' | 'Low Stock' | 'Out of Stock';
}

export interface Testimonial {
  name: string;
  location: string;
  comment: string;
  avatar: string;
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Sheo (Shoe) brake',
    description: 'High-quality shoe brake for effective stopping power.',
    price: 3500,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'brake shoe',
    rating: 4.5,
    reviewsCount: 112,
    stockStatus: 'In Stock',
  },
  {
    id: '2',
    name: 'Clutch cable',
    description: 'Durable clutch cable for smooth gear shifting.',
    price: 4000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'clutch cable',
    rating: 4.6,
    reviewsCount: 98,
    stockStatus: 'In Stock',
  },
  {
    id: '3',
    name: 'Clutch plate',
    description: 'Genuine clutch plate for optimal power transmission.',
    price: 12000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'clutch plate',
    rating: 4.7,
    reviewsCount: 85,
    stockStatus: 'In Stock',
  },
  {
    id: '4',
    name: 'Brake pads',
    description: 'Reliable brake pads for safe and consistent braking.',
    price: 6000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'brake pads',
    rating: 4.5,
    reviewsCount: 150,
    stockStatus: 'In Stock',
  },
  {
    id: '5',
    name: 'Engine block (used/local)',
    description: 'Used local engine block for Keke.',
    price: 120000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'engine block',
    rating: 3.9,
    reviewsCount: 25,
    stockStatus: 'Low Stock',
  },
  {
    id: '6',
    name: 'Gearbox',
    description: 'Complete gearbox assembly for Keke.',
    price: 85000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'keke gearbox',
    rating: 4.2,
    reviewsCount: 42,
    stockStatus: 'In Stock',
  },
  {
    id: '7',
    name: 'Drive shaft / axle',
    description: 'Sturdy drive shaft/axle for Keke rear wheels.',
    price: 35000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'drive shaft',
    rating: 4.4,
    reviewsCount: 38,
    stockStatus: 'In Stock',
  },
  {
    id: '8',
    name: 'Battery (12V, Keke size)',
    description: 'Long-lasting 12V battery designed for Keke.',
    price: 32000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'keke battery',
    rating: 4.6,
    reviewsCount: 78,
    stockStatus: 'In Stock',
  },
  {
    id: '9',
    name: 'Starter motor',
    description: 'Powerful starter motor for reliable engine ignition.',
    price: 40000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'starter motor',
    rating: 4.3,
    reviewsCount: 55,
    stockStatus: 'In Stock',
  },
  {
    id: '10',
    name: 'Alternator',
    description: 'High-output alternator to keep your battery charged.',
    price: 35000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'car alternator',
    rating: 4.2,
    reviewsCount: 49,
    stockStatus: 'In Stock',
  },
  {
    id: '11',
    name: 'Radiator',
    description: 'Efficient radiator for optimal engine cooling.',
    price: 45000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'car radiator',
    rating: 4.5,
    reviewsCount: 63,
    stockStatus: 'In Stock',
  },
  {
    id: '12',
    name: 'Fuel pump',
    description: 'Reliable fuel pump for consistent fuel delivery.',
    price: 15000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'fuel pump',
    rating: 4.1,
    reviewsCount: 72,
    stockStatus: 'In Stock',
  },
  {
    id: '13',
    name: 'Carburetor',
    description: 'High-performance carburetor for better fuel mixture.',
    price: 20000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'keke carburetor',
    rating: 4.3,
    reviewsCount: 91,
    stockStatus: 'In Stock',
  },
  {
    id: '14',
    name: 'Front shock absorber (1pc)',
    description: 'Front shock absorber for a smoother ride.',
    price: 15000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'shock absorber',
    rating: 4.6,
    reviewsCount: 123,
    stockStatus: 'In Stock',
  },
  {
    id: '15',
    name: 'Rear shock absorber',
    description: 'Durable rear shock absorber for stability and comfort.',
    price: 18000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'shock absorber',
    rating: 4.5,
    reviewsCount: 110,
    stockStatus: 'In Stock',
  },
  {
    id: '16',
    name: 'Leaf spring',
    description: 'Heavy-duty leaf spring for supporting heavy loads.',
    price: 25000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'leaf spring',
    rating: 4.7,
    reviewsCount: 88,
    stockStatus: 'In Stock',
  },
  {
    id: '17',
    name: 'Spring pin (set)',
    description: 'Complete set of spring pins for suspension maintenance.',
    price: 5000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'metal pin',
    rating: 4.4,
    reviewsCount: 45,
    stockStatus: 'In Stock',
  },
  {
    id: '18',
    name: 'Tyre (12-inch Keke tire)',
    description: 'High-quality 12-inch tire for Keke.',
    price: 18000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'motorcycle tire',
    rating: 4.8,
    reviewsCount: 230,
    stockStatus: 'In Stock',
  },
  {
    id: '19',
    name: 'Rim (1pc, steel)',
    description: 'Sturdy steel rim for Keke wheels.',
    price: 15000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'wheel rim',
    rating: 4.5,
    reviewsCount: 65,
    stockStatus: 'In Stock',
  },
  {
    id: '20',
    name: 'Headlamp assembly (pair)',
    description: 'Bright headlamp assembly for safe night driving.',
    price: 16000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'keke headlight',
    rating: 4.7,
    reviewsCount: 95,
    stockStatus: 'In Stock',
  },
  {
    id: '21',
    name: 'Tail light',
    description: 'Durable tail light for clear signaling.',
    price: 6000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'tail light',
    rating: 4.4,
    reviewsCount: 75,
    stockStatus: 'In Stock',
  },
  {
    id: '22',
    name: 'Side mirror (1pc)',
    description: 'Clear side mirror for better visibility.',
    price: 5000,
    category: 'Accessories',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'side mirror',
    rating: 4.3,
    reviewsCount: 115,
    stockStatus: 'In Stock',
  },
  {
    id: '23',
    name: 'Full body panel set',
    description: 'Complete set of body panels to refresh your Keke.',
    price: 85000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'metal panel',
    rating: 4.1,
    reviewsCount: 30,
    stockStatus: 'Out of Stock',
  },
  {
    id: '24',
    name: 'Fender (per piece)',
    description: 'Protective fender for Keke wheels.',
    price: 12000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'car fender',
    rating: 4.2,
    reviewsCount: 50,
    stockStatus: 'In Stock',
  },
  {
    id: '25',
    name: 'Seat cover',
    description: 'Comfortable and stylish seat cover.',
    price: 6000,
    category: 'Accessories',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'seat cover',
    rating: 4.6,
    reviewsCount: 180,
    stockStatus: 'In Stock',
  },
  {
    id: '26',
    name: 'Floor mat set',
    description: 'Durable floor mat set to keep your Keke clean.',
    price: 4000,
    category: 'Accessories',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'floor mat',
    rating: 4.5,
    reviewsCount: 130,
    stockStatus: 'In Stock',
  },
  {
    id: '27',
    name: 'Spark plug',
    description: 'Reliable spark plug for efficient combustion.',
    price: 800,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'spark plug',
    rating: 4.8,
    reviewsCount: 350,
    stockStatus: 'In Stock',
  },
  {
    id: '28',
    name: 'Ignition coil',
    description: 'High-performance ignition coil for a strong spark.',
    price: 4000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'ignition coil',
    rating: 4.4,
    reviewsCount: 90,
    stockStatus: 'In Stock',
  },
  {
    id: '29',
    name: 'Fire extinguisher (1kg)',
    description: 'Essential 1kg fire extinguisher for safety.',
    price: 5000,
    category: 'Accessories',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'fire extinguisher',
    rating: 4.9,
    reviewsCount: 200,
    stockStatus: 'In Stock',
  },
  {
    id: '30',
    name: 'Car jack (mechanical)',
    description: 'Mechanical car jack for emergency repairs.',
    price: 10000,
    category: 'Accessories',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'car jack',
    rating: 4.7,
    reviewsCount: 140,
    stockStatus: 'In Stock',
  },
  {
    id: '31',
    name: 'GPS Tracker (basic)',
    description: 'Basic GPS tracker for vehicle security.',
    price: 7000,
    category: 'Accessories',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'gps tracker',
    rating: 4.2,
    reviewsCount: 80,
    stockStatus: 'Low Stock',
  },
  {
    id: '32',
    name: 'CNG conversion kit',
    description: 'Kit to convert your Keke to run on CNG.',
    price: 110000,
    category: 'Spare Parts',
    brand: 'Generic',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'CNG kit',
    rating: 4.0,
    reviewsCount: 15,
    stockStatus: 'Out of Stock',
  },
  {
    id: '33',
    name: 'Bajaj RE 4S Keke',
    description: 'A brand new, reliable Bajaj RE 4S tricycle, perfect for commercial transport. Comes with a powerful engine and durable body.',
    price: 850000,
    category: 'Keke Models',
    brand: 'Bajaj',
    image: 'https://placehold.co/400x400.png',
    aiHint: 'new tricycle',
    rating: 4.8,
    reviewsCount: 152,
    stockStatus: 'In Stock',
  },
];


export const testimonials: Testimonial[] = [
  {
    name: 'Musa Garba',
    location: 'Kano',
    comment: 'Anointed Multilinks is the only place I trust for my Keke parts. They are genuine and the delivery is very fast. My business has improved since I started buying from them.',
    avatar: 'https://placehold.co/100x100.png',
  },
  {
    name: 'Chinedu Okafor',
    location: 'Onitsha',
    comment: 'The quality of their parts is top-notch. I bought a carburetor from them, and my Keke is running smoother than ever. Highly recommended for all mechanics.',
    avatar: 'https://placehold.co/100x100.png',
  },
  {
    name: 'Adekunle Johnson',
    location: 'Lagos',
    comment: 'Excellent customer service! The AI assistant helped me find the exact part I needed when I didn\'t even know the name. It saved me a lot of time and stress.',
    avatar: 'https://placehold.co/100x100.png',
  },
];
